version: '3.8'

x-shared-environment: &commonEnv
    REDIS_HOST: "cache"
    REDIS_PORT: 6379

services:
    ui:
        container_name: 'ui'
        build:
          context: './ui'
          args:
            NODE_ENV: 'production'
            REACT_APP_HOST_API: 'http://localhost:8080/api/v1'
            REACT_APP_HOST_AUTH: 'http://localhost:10090/v1'
        ports:
          - '80:80'
        networks:
          - operational_network

networks:
    operational_network:
        name: operational_network
        driver: bridge